"""Architecture diagrams for Uliza Kahawa, written as code (Graphviz via the `diagrams` library), not drawn by hand
or generated by an image model, so they stay in step with the code.

  pip install diagrams      # plus Graphviz (brew install graphviz / apt install graphviz)
  python3 docs/diagrams/make_diagrams.py

Writes four PNGs next to this file:
  01_overview       who uses it, on which phone, and where the AI runs
  02_decision       what happens to one message (answer / did you mean / a person)
  03_data           where each piece of data lives, what leaves the phone, and build time vs run time
  04_build          how the model, answers and audio are built and tested
"""
import os

from diagrams import Cluster, Diagram, Edge
from diagrams.generic.device import Mobile
from diagrams.generic.storage import Storage
from diagrams.onprem.client import User, Users
from diagrams.onprem.compute import Server
from diagrams.programming.flowchart import (Action, Database, Decision, Document, InputOutput, MultipleDocuments,
                                            PredefinedProcess, StartEnd, StoredData)
from diagrams.programming.language import Javascript, Python

HERE = os.path.dirname(os.path.abspath(__file__))
G = {"fontsize": "13", "bgcolor": "white", "pad": "0.5", "nodesep": "0.55", "ranksep": "0.9", "splines": "spline"}
N = {"fontsize": "11"}
GREEN, AMBER, GREY, RED = "#2F6B4F", "#B7791F", "#8A8478", "#9B2C2C"


def out(name):
    return os.path.join(HERE, name)


# ---------------------------------------------------------------- 1. overview
with Diagram("Uliza Kahawa: one small AI, two kinds of phone", filename=out("01_overview"), show=False,
             direction="LR", graph_attr=G, node_attr=N):
    noor = User("Coffee farmer\n(Kiswahili / English)")

    with Cluster("Household phone (KaiOS or smartphone): works with NO internet"):
        app = Javascript("Offline web app\n(model.js + channels.js)")
        model_p = StoredData("Model 279 KB\n+ 12 expert answers\n+ audio 1.4 MB")
        log = Storage("Questions on the phone\n(consent, clear any time)")
        app - Edge(style="dashed", color=GREY) - model_p
        app >> Edge(label="saved", color=GREY) >> log

    with Cluster("Basic phone (Nokia 105 type): needs signal, NO data"):
        basic = Mobile("USSD *384*2026#\nSMS · voice call")

    with Cluster("Behind the code / number (same code as the app)"):
        server = Server("ussd/server.js\nsame model + answers\nreply < 1 ms (limit ~10 s)")

    with Cluster("People who decide"):
        officer = Users("Cooperative /\nextension officer")

    noor >> Edge(label="types or speaks\nher question", color=GREEN) >> app
    noor >> Edge(label="dials / texts / calls", color=GREEN) >> basic
    basic >> Edge(label="USSD / SMS", color=GREEN) >> server
    log >> Edge(label="unsure questions, by SMS\nwhen a signal appears", color=AMBER) >> officer
    server >> Edge(label="unsure questions", color=AMBER) >> officer
    officer >> Edge(label="calls back", style="dashed", color=GREY) >> noor


# ---------------------------------------------------------------- 2. one message
with Diagram("What happens to one message", filename=out("02_decision"), show=False, direction="LR",
             graph_attr={**G, "ranksep": "0.7"}, node_attr=N):
    msg = InputOutput("\"majani yana unga\nwa njano chini\"")
    norm = Action("Normalise\n(lower case, accents,\npunctuation)")
    feats = Action("Hashed word +\ncharacter n-grams\n(16,384 buckets)")
    clf = PredefinedProcess("Softmax classifier\nint8 weights\n12 topics + 'none'")
    sure = Decision("Top topic\n≥ 86% sure?")
    coffee = Decision("Unsure between\ncoffee topics?")
    ans = Document("Expert answer for\nthat topic\n(text + audio)")
    ask = Decision("\"Did you mean\n1 … 2 … 0 a person\"\n(farmer chooses)")
    person = Database("\"I can only help with…\"\nquestion saved for\nthe extension officer")

    msg >> norm >> feats >> clf >> sure
    sure >> Edge(label="yes", color=GREEN) >> ans
    sure >> Edge(label="no", color=AMBER) >> coffee
    coffee >> Edge(label="yes", color=AMBER) >> ask
    coffee >> Edge(label="no: off-topic,\nKikuyu, other crops", color=RED) >> person
    ask >> Edge(label="picks a topic", color=GREEN) >> ans
    ask >> Edge(label="0", color=AMBER) >> person


# ---------------------------------------------------------------- 3. data
with Diagram("Where the data lives", filename=out("03_data"), show=False, direction="LR", graph_attr=G, node_attr=N):
    with Cluster("BUILD TIME only (our laptop; never in the product)"):
        pub = MultipleDocuments("Public data\nKALRO / FAO sources, MASSIVE,\nFLORES-200, World Bank prices,\nNASA POWER, FAOSTAT")
        gem = Python("Gemini (grounded search,\nsynthetic training messages)")
        el = Python("ElevenLabs\n(demo voice)")
        build = PredefinedProcess("build.py · train.py\nvoice.py")
        pub >> build
        gem >> Edge(style="dashed", color=GREY) >> build
        el >> Edge(style="dashed", color=GREY) >> build

    with Cluster("ON THE PHONE (run time)"):
        bundle = StoredData("model.json · answers ·\naudio (cached offline)")
        qlog = Storage("Her questions + results\n(local only; 'clear my\nquestions' deletes them)")
        no_ai = StartEnd("The model runs here:\nno AI service sees\nany farmer data")

    with Cluster("LEAVES THE PHONE (only with consent)"):
        sms = InputOutput("Unsure question, her words\n+ her number, by SMS")
        officer = Users("Cooperative's\nextension officer")

    with Cluster("Basic-phone server"):
        srv = Server("Stores NO phone number\n(last 2 digits in the demo)\nlogs: topic + reply time only")

    build >> Edge(label="side-load / one download", color=GREEN) >> bundle
    bundle - Edge(style="dashed", color=GREY) - qlog
    qlog >> Edge(label="consent = yes", color=AMBER) >> sms >> officer
    srv >> Edge(label="unsure questions", color=AMBER) >> officer
    bundle - Edge(style="invis") - no_ai


# ---------------------------------------------------------------- 4. build + test
with Diagram("How it is built and checked", filename=out("04_build"), show=False, direction="LR", graph_attr=G,
             node_attr=N):
    fetch = Python("data/fetch.py\n(6 public sources\n+ manifest)")
    answers = Document("answers.json\n12 vetted answers\n(sw + en, sourced)")
    abuild = Python("answers/build.py\nlength + source checks,\nlive Arabica price")
    voice = Python("answers/voice.py\n26 recordings")
    ex = MultipleDocuments("examples.py (258 hand)\n+ examples_gemini (480)\n+ MASSIVE / near-miss 'none'")
    train = Python("models/train.py\n5-fold CV, held-out,\nthreshold, int8 export")
    model = StoredData("model.json\n279 KB")
    tests = PredefinedProcess("kikuyu.py · baseline.py\nparity.py (303/303)\nussd_test.js (19/19)")
    app = Javascript("app/ + ussd/\n(same model.js,\nsame channels.js)")

    fetch >> abuild
    answers >> abuild >> voice
    ex >> train >> model
    abuild >> app
    voice >> app
    model >> app
    model >> tests
    app >> Edge(style="dashed", color=GREY) >> tests

print("wrote 01_overview.png, 02_decision.png, 03_data.png, 04_build.png")
